parameters:
#    dcl_frontend.example.class: DCL\FrontendBundle\Example

services:
#    dcl_frontend.example:
#        class: %dcl_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
